import httpx
import json

def main():
    with httpx.Client(base_url="http://localhost:8000", timeout=120.0) as client:
        # 1. Health check
        h = client.get("/")
        print("1. HEALTH CHECK:", h.status_code, h.json(), flush=True)

        # 2. Register/Login
        reg_resp = client.post("/auth/register", json={
            "email": "live_operator@logistics.com",
            "password": "SecurePassword123!",
            "name": "Live Fleet Manager"
        })
        print("2. REGISTRATION:", reg_resp.status_code, flush=True)

        login_resp = client.post("/auth/login", data={
            "username": "live_operator@logistics.com",
            "password": "SecurePassword123!"
        })
        print("3. LOGIN:", login_resp.status_code, flush=True)
        token = login_resp.json().get("access_token")
        headers = {"Authorization": f"Bearer {token}"}

        # 4. Shipments
        sh_resp = client.get("/shipments", headers=headers)
        shipments = sh_resp.json().get("shipments", [])
        print(f"4. LIVE SHIPMENTS (MongoDB): {len(shipments)} active shipments", flush=True)
        if shipments:
            print(f"   Sample: {shipments[0]['shipment_id']} ({shipments[0]['origin']} -> {shipments[0]['destination']} via {shipments[0]['route_highway']})", flush=True)

        # 5. Disruptions
        print("5. FETCHING LIVE DISRUPTIONS (OpenWeatherMap + GNews)...", flush=True)
        dis_resp = client.get("/disruptions", headers=headers)
        disruptions = dis_resp.json().get("disruptions", [])
        print(f"   Received {len(disruptions)} active signals", flush=True)
        for d in disruptions[:3]:
            print(f"   - {d.get('location')}: {d.get('subtype')} | Source: {d.get('source')}", flush=True)

        # 6. Full 4-Agent Risk Analysis with Gemini 3.6 Flash
        print("\n6. EXECUTING LIVE 4-AGENT PIPELINE WITH GEMINI 3.6 FLASH...", flush=True)
        ra_resp = client.get("/risk-analysis", headers=headers)
        print(f"   Status: {ra_resp.status_code}", flush=True)
        ra_data = ra_resp.json()
        print("   Pipeline stats:", ra_data.get("pipeline"), flush=True)

        recs = ra_data.get("recommendations", [])
        gemini_recs = [r for r in recs if r.get("recommendation_by") == "gemini-3.6-flash"]
        safe_recs = [r for r in recs if r.get("risk_level") == "SAFE"]
        
        print(f"\n7. AI VALIDATION SUMMARY:", flush=True)
        print(f"   Total shipments evaluated: {len(recs)}", flush=True)
        print(f"   Gemini-3.6-flash recommendations generated: {len(gemini_recs)}", flush=True)
        print(f"   Safe shipments (no reroute needed): {len(safe_recs)}", flush=True)

        if gemini_recs:
            r = gemini_recs[0]
            print(f"\n   === SAMPLE LIVE GEMINI RECOMMENDATION ===", flush=True)
            print(f"   Shipment: {r.get('shipment_id')} | Risk Level: {r.get('risk_level')}", flush=True)
            print(f"   Disruption: {r.get('disruption_type')} at {r.get('disruption_location')} ({r.get('distance_to_disruption_km')} km away)", flush=True)
            print(f"   Suggested Action: {r.get('suggested_action')}", flush=True)
            print(f"   Alternate Route: {r.get('alternate_route')}", flush=True)
            print(f"   Estimated Delay: {r.get('estimated_delay_hours')} hours", flush=True)
            print(f"   Customer Message: {r.get('customer_message')}", flush=True)
            print(f"   Generated By: {r.get('recommendation_by')}", flush=True)

if __name__ == "__main__":
    main()
